quarkus:
  http:
    cors: true
  container-image:
    registry: image-registry.openshift-image-registry.svc:5000
    group: alexa
  kubernetes:
    deployment-target: knative, openshift
  knative:
    ports:
      http1:
        container-port: 8080
  openshift:
    ports:
      http1:
        container-port: 8080
  log:
    category:
      "org.jboss.resteasy.tracing.api.RESTEasyTracing":
          level: FINE
compughter-ratings/mp-rest/url: http://hackfest-api-amendment-alexa.apps.cluster-fed2.fed2.example.opentlc.com
compughter-ratings/mp-rest/scope: javax.inject.Singleton
app:
  app-id: IUGe17QzIejCMI4KdQ11vLhAfBMx7uP7
  api-key: FsvhlOuyRBkTpWKxkrq4cJLyFZ1omdNT
