quarkus:
  http:
    cors: true
  container-image:
    registry: image-registry.openshift-image-registry.svc:5000
    group: bookie
  kubernetes:
    deployment-target: knative, openshift
  knative:
    ports:
      http1:
        container-port: 8080
  openshift:
    ports:
      http1:
        container-port: 8080
  log:
    category:
      "org.jboss.resteasy.tracing.api.RESTEasyTracing":
          level: FINE
compughter-ratings/mp-rest/url: http://hackfest-api-amendment-bookie.apps.cluster-ae02.ae02.sandbox1545.opentlc.com
compughter-ratings/mp-rest/scope: javax.inject.Singleton
prediction/mp-rest/url: http://spring-data-jpa-quickstart-bookie.apps.cluster-ae02.ae02.sandbox1545.opentlc.com
prediction/mp-rest/scope: javax.inject.Singleton
app:
  app-id: zlKotUlt4cMwTSVd3yhLmz7vmZlkEoP5
  api-key: lcuYc0RnCaBDUNQXA0vCc390kelTKrNI

#mp:
#  messaging:
#    outgoing:
#      predictions:
#        connector: smallrye-kafka
#        topic: predictions
#        value:
#          serializer: io.vertx.kafka.client.serialization.JsonObjectSerializer
#        "boostrap.servers": kafka-kafka-bootstrap:9092
     
