quarkus:
  log:
    category:
      "org.jboss.resteasy.tracing.api.RESTEasyTracing":
          level: FINE
compughter-ratings/mp-rest/url: http://hackfest-api-amendment-alexa.apps.cluster-fed2.fed2.example.opentlc.com
compughter-ratings/mp-rest/scope: javax.inject.Singleton
app:
  app-id: IUGe17QzIejCMI4KdQ11vLhAfBMx7uP7
  api-key: FsvhlOuyRBkTpWKxkrq4cJLyFZ1omdNT