apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: predictions
  lables:
    strimzi.io/cluster: kafka
  namespace: alexa
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 6048000000
    segment.bytes: 1073741824