apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: simulation
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 

