apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic predictions suing consumer group my-group
      - resource:
          type: topic
          name: predictions
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: predictions
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: bookie
          patternType: literal
        operation: Read
        host: "*"
      # Example Producer Acls for topic predictions
      - resource:
          type: topic
          name: predictions
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: predictions
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: predictions
          patternType: literal
        operation: Describe
        host: "*"